---
abstract: 'WWW::Shorten plugin for URLchen.de'
author:
  - 'Danijel Tasov <data@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Shorten-URLchen
provides:
  WWW::Shorten::URLchen:
    file: lib/WWW/Shorten/URLchen.pm
    version: v0.0.3
requires:
  Carp: 0
  Exporter: 0
  WWW::Shorten: 3.00
  base: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/datamuc/WWW-Shorten-URLchen
version: v0.0.3
